[package]
name = "subkey"
version = "0.2.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
substrate-primitives = { version = "*", path = "../core/primitives" }
rand = "0.4"
clap = { version = "~2.32", features = ["yaml"] }
num_cpus = "1.8.0"
pbr = "1.0.1"

[features]
bench = []
